---
# On Debian, php-* install directly php v7.x now
__php_packages:
  - php-common
  - php-cli
  - php-dev
  - php-fpm
  - libpcre3-dev
  - php-gd
  - php-curl
  - php-imap
  - php-json
  - php-opcache
  - php-xml
  - php-mbstring
  - php-mysql
  - php-ldap
  - php-apcu
__php_webserver_daemon: "apache2"

# Vendor-specific configuration paths on Debian/Ubuntu make my brain asplode.
__php_conf_paths:
  - /etc/php/7.0/fpm
  - /etc/php/7.0/apache2
  - /etc/php/7.0/cli

__php_extension_conf_paths:
  - /etc/php/7.0/fpm/conf.d
  - /etc/php/7.0/apache2/conf.d
  - /etc/php/7.0/cli/conf.d

__php_apc_conf_filename: 20-apcu.ini
__php_opcache_conf_filename: 05-opcache.ini
__php_fpm_daemon: php7.0-fpm
__php_fpm_conf_path: "/etc/php/7.0/fpm"
__php_fpm_pool_conf_path: "{{ __php_fpm_conf_path }}/pool.d/www.conf"

__php_fpm_pool_user: www-data
__php_fpm_pool_group: www-data
